output-format: grouped

strictness: veryhigh
doc-warnings: true
test-warnings: false
max-line-length: 120

autodetect: false
uses:
    - flask

ignore-paths:
  - docs/

frosted:
  run: false

pyroma:
  run: true

mypy:
  run: true
  options:
    ignore-missing-imports: true
    follow-imports: skip

pylint:
  disable:
    - bad-builtin
    - too-few-public-methods
    - missing-docstring
    - star-args
    - import-error
    - too-many-return-statements

pep8:
  full: true
  disable:
    - E126

pep257:
  disable:
    - D100
    - D101
    - D102
    - D103
    - D205
    - D400
    - D401
    - D212
  enable:
    - D213

mccabe:
  run: false

dodgy:
  run: true

pyflakes:
  run: true

vulture:
  run: false
